version: '3.9'

services:
  backend:
    build:
      context: ./Servers
      dockerfile: Dockerfile.dev

  frontend:
    build:
      context: ./Clients
      dockerfile: Dockerfile.dev
    ports:
      - $FRONTEND_PORT:$FRONTEND_PORT
    environment:
      - VITE_APP_PORT=$FRONTEND_PORT
