name: Build and Push Images to GitHub Container Registry

on:
  push:
    branches:
      # - master
      - hp-may-16-push-images-to-ghcr

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Debug GitHub Token Access
        run: |
          if [ -z "${{ secrets.GITHUB_TOKEN }}" ]; then
            echo "GITHUB_TOKEN is NOT available"
            exit 1
          else
            echo "GITHUB_TOKEN is available"
          fi

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Clients image
        uses: docker/build-push-action@v4
        with:
          context: ./Clients
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/verifywise-frontend:test

      - name: Build and push Servers image
        uses: docker/build-push-action@v4
        with:
          context: ./Servers
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/verifywise-backend:test
